build:
  environment:
    php: 7.2
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
          - command: vendor/bin/phpunit --coverage-clover 'coverage/clover.xml'
            coverage:
              file: coverage/clover.xml
              format: clover
filter:
  paths:
    - src/

  dependency_paths:
    - vendor/

  excluded_paths:
    - tests/
    - stub/
